server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      #这里的端口是EurekaServer端的端口
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
spring:
  application:
    name: eureka-client
